name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run : git remote set-url origin https://tamiberti:$PAT@github.com/tamiberti/tamiberti.github.io.git && git config --global user.name github-actions && git config --global user.email tamisberti@gmail.com && npm i && npm run deploy -- -m "Deploy React app to GitHub Pages"
      shell: bash
      
